[project]
name = "negotiaai-deployable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.1.2",
    "flask-cors==6.0.1",
    "gunicorn>=25.0.3",
    "joblib==1.4.2",
    "numpy==2.3.2",
    "pandas==2.3.2",
]
